Add Probono's changes to our recipe

diff --git a/recipes/krita/Recipe b/recipes/krita/Recipe
--- a/recipes/krita/Recipe
+++ b/recipes/krita/Recipe
@@ -19,22 +19,24 @@ grep -r "CentOS release 6" /etc/redhat-release || exit 1
 export LC_ALL=en_US.UTF-8
 export LANG=en_us.UTF-8
 
+# Determine which architecture should be built
+if [[ "$(arch)" = "i686" || "$(arch)" = "x86_64" ]] ; then
+  ARCH=$(arch)
+else
+  echo "Architecture could not be determined"
+  exit 1
+fi
+
 # if the library path doesn't point to our usr/lib, linking will be broken and we won't find all deps either
 export LD_LIBRARY_PATH=/usr/lib64/:/usr/lib:/krita.appdir/usr/lib
 
 git_pull_rebase_helper()
 {
-	GITCLEAN=$(git diff --shortstat 2> /dev/null | tail -n1)
-	if [ "x$GITCLEAN" != "x" ] ; then
-		git stash save
-		git pull --rebase
-		git stash pop
-	else
-		git pull --rebase
-	fi
+	git reset --hard HEAD
+        git pull
 }
 
-#if [ -z "$NO_DOWNLOAD" ] ; then
+if [ -z "$NO_DOWNLOAD" ] ; then
 yum -y install epel-release 
 # we need to be up to date in order to install the xcb-keysyms dependency
 yum -y update
@@ -57,7 +59,7 @@ cd /AppImageKit/
 git_pull_rebase_helper
 ./build.sh
 cd /
-#fi
+fi # [ -z "$NO_DOWNLOAD" ]
 
 
 # Workaround for:
@@ -180,18 +182,26 @@ cp $(ldconfig -p | grep libEGL.so.1 | cut -d ">" -f 2 | xargs) ./usr/lib/ # Othe
 cp $(ldconfig -p | grep libxcb.so.1 | cut -d ">" -f 2 | xargs) ./usr/lib/ 
 cp $(ldconfig -p | grep libfreetype.so.6 | cut -d ">" -f 2 | xargs) ./usr/lib/ # For Fedora 20
 
-#ldd usr/bin/krita | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true
+ldd usr/bin/krita | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true
 #ldd usr/lib64/krita/*.so  | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true
 #ldd usr/lib64/plugins/imageformats/*.so  | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true
-
 
 ldd usr/lib/qt5/plugins/platforms/libqxcb.so | grep "=>" | awk '{print $3}'  |  xargs -I '{}' cp -v '{}' ./usr/lib || true
 
 # Copy in the indirect dependencies
 FILES=$(find . -type f -executable)
+DEPS=""
 for FILE in $FILES ; do
-  ldd "${FILE}" | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' usr/lib || true
+  ldd "${FILE}" | grep "=>" | awk '{print $3}' | xargs -I '{}' echo '{}' > DEPSFILE
 done
+DEPS=$(cat DEPSFILE  |sort | uniq)
+for FILE in $DEPS ; do
+  if [ -f $FILE ] ; then
+    echo $FILE
+    cp --parents -rfL $FILE ./
+  fi
+done
+rm -f DEPSFILE
 
 
 # The following are assumed to be part of the base system
@@ -289,8 +299,6 @@ cd ..
 VERSION=$VER-$BRANCH-$REVISION
 VERSION="$(sed s/\ /-/g <<<$VERSION)"
 echo $VERSION
-
-ARCH=$(arch)
 
 if [[ "$ARCH" = "x86_64" ]] ; then
 	APPIMAGE=$APP"-"$VERSION"-x86_64.AppImage"
